FROM hexpm/elixir:1.3.4-erlang-18.3.4.11-debian-stretch-20200511

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        make \
        wget \
        git \
        ca-certificates \
        openssh-client \
        build-essential \
        openssl \
        locales && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    echo "LANG=en_US.UTF-8" > /etc/locale.conf && \
    locale-gen en_US.UTF-8 && \
    update-ca-certificates

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    MIX_HOME=/cache/.mix \
    HEX_HOME=/cache/.hex \
    DEBIAN_FRONTEND=noninteractive

ARG USER_ID
ARG GROUP_ID

RUN groupadd --gid $GROUP_ID user && \
    useradd -m --gid $GROUP_ID --uid $USER_ID user && \
    mkdir -p /cache && chown user:user /cache

USER user
WORKDIR /home/user

RUN mkdir app
RUN mix local.hex --force
RUN mix local.rebar

COPY get-old-phx .
RUN bash get-old-phx

WORKDIR /home/user/app

CMD ["/bin/bash"]
