defmodule Utility.GenDiff.Markdown do
  @moduledoc """
  Builds the LLM-facing documents for a generated diff.

  `index/3` is a compact document — a "how to use" preamble, generator metadata, a
  change summary, and a list of changed files, each linking to its own patch URL.
  Full patches can run to hundreds of KB, which blows an LLM's context, so the model
  fetches the index and then pulls only the per-file patches it needs via `file_patch/2`.
  """
  alias Utility.GenDiff.Generator

  @doc """
  The index document. `file_url` is a 1-arity function mapping a file path to the
  absolute URL of that file's patch.
  """
  @spec index(Generator.t(), binary(), (binary() -> binary()), binary() | nil) :: binary()
  def index(%Generator{} = generator, patch, file_url, changelog_url \\ nil)
      when is_function(file_url, 1) do
    entries = file_entries(patch)

    """
    # gendiff: `#{generator.command}` — #{generator.from_version} → #{generator.to_version}

    #{preamble(generator)}

    #{metadata(generator)}

    #{changelog_section(changelog_url)}

    #{summary(entries)}

    #{file_list(entries, generator, file_url)}
    """
  end

  @doc "Per-file entries (`path`, `additions`, `deletions`) parsed from a unified patch."
  @spec file_entries(binary()) :: [
          %{path: binary(), additions: non_neg_integer(), deletions: non_neg_integer()}
        ]
  def file_entries(patch) do
    patch
    |> split_files()
    |> Enum.map(fn chunk ->
      %{
        path: file_path(chunk),
        additions: count_lines(chunk, "+", "+++"),
        deletions: count_lines(chunk, "-", "---")
      }
    end)
  end

  @doc "The standalone unified diff for a single file path, or `nil` if not in the patch."
  @spec file_patch(binary(), binary()) :: binary() | nil
  def file_patch(patch, path) do
    patch
    |> split_files()
    |> Enum.find_value(fn chunk ->
      if file_path(chunk) == path, do: "diff --git " <> String.trim_trailing(chunk) <> "\n"
    end)
  end

  defp preamble(generator) do
    """
    ## How to use this document

    This is an **index** of what changed in a freshly-generated app when running
    `#{generator.command}` at version #{generator.from_version} versus #{generator.to_version}
    with the flags listed below. Each file's diff lives at its own URL — **fetch only the
    files relevant to your task** rather than all of them. It is a **reference for
    upgrading**, not a script to apply verbatim.

    - The diff is a **clean, newly-scaffolded app**. A real app has customizations a fresh app does not.
    - **Adapt** each change to the target app; do not copy-paste wholesale.
    - **Do not delete** code merely because it is absent here — it may have been added deliberately.
    - Changes assume **these exact flags**. Different flags produce different output.
    """
  end

  defp metadata(generator) do
    """
    ## Generator metadata

    - **project:** `#{generator.project}`
    - **command:** `#{generator.command}`
    - **from:** `#{generator.from_version}` — flags: #{format_flags(generator.from_flags)}
    - **to:** `#{generator.to_version}` — flags: #{format_flags(generator.to_flags)}
    """
  end

  defp changelog_section(nil) do
    "## Changelog\n\n_No changelog is available for this generator._\n"
  end

  defp changelog_section(url) do
    """
    ## Changelog — ⚠️ ALWAYS READ THIS FIRST

    Before looking at any file diffs, **fetch and read the changelog** below. It explains
    the release's intent, new features, deprecations, and breaking changes that the diffs
    alone won't convey:

    #{url}
    """
  end

  defp summary(entries) do
    additions = Enum.sum(Enum.map(entries, & &1.additions))
    deletions = Enum.sum(Enum.map(entries, & &1.deletions))

    """
    ## Summary of changes

    - **files changed:** #{length(entries)}
    - **lines added:** #{additions}
    - **lines removed:** #{deletions}
    """
  end

  defp file_list([], _generator, _file_url) do
    """
    ## Files

    _No differences between the two generated apps for these flags._
    """
  end

  defp file_list(entries, generator, file_url) do
    {vendored, important} = Enum.split_with(entries, &vendored?(generator.project, &1.path))

    """
    ## Files

    Each file's diff is at its own URL below. Fetch only the ones relevant to your task.

    #{rows(important, file_url)}
    #{vendored_section(vendored, file_url)}
    """
  end

  defp vendored_section([], _file_url), do: ""

  defp vendored_section(entries, file_url) do
    """

    ### Framework-managed / vendored assets (usually safe to skip)

    These are installed and regenerated by dependencies (e.g. `tailwind`, `esbuild`,
    `heroicons`, `daisyui`) when you upgrade — you normally don't apply their diffs by
    hand. Only look if you've customized them.

    #{rows(entries, file_url)}
    """
  end

  defp rows(entries, file_url) do
    Enum.map_join(entries, "\n", fn entry ->
      "- [`#{entry.path}`](#{file_url.(entry.path)}) — +#{entry.additions} −#{entry.deletions}"
    end)
  end

  # Phoenix (`phx_new`) vendors third-party JS/CSS under assets/vendor/ — those files
  # come from bumping deps, not hand-editing, so they're noise for an upgrade.
  defp vendored?("phx_new", path), do: String.starts_with?(path, "assets/vendor/")
  defp vendored?(_project, _path), do: false

  defp count_lines(chunk, prefix, exclude) do
    chunk
    |> String.split("\n")
    |> Enum.count(&(String.starts_with?(&1, prefix) and not String.starts_with?(&1, exclude)))
  end

  defp split_files(""), do: []
  defp split_files(patch), do: String.split(patch, ~r/^diff --git /m, trim: true)

  # First line of a chunk is "a/PATH b/PATH2"; prefer the "to" path unless it's /dev/null.
  defp file_path(chunk) do
    first_line = chunk |> String.split("\n", parts: 2) |> hd()

    case Regex.run(~r{^a/(\S+) b/(\S+)}, first_line) do
      [_, from, "dev/null"] -> from
      [_, _from, to] -> to
      _ -> String.trim(first_line)
    end
  end

  defp format_flags([]), do: "_(none)_"
  defp format_flags(flags), do: "`#{Enum.join(flags, " ")}`"
end
